dev:
  commands:
    - command: go mod download
      directory: services
      name: install cmd
    - command: python -m venv --copies ~/.venv && . ~/.venv/bin/activate && pip
        install poetry==$NIXPACKS_POETRY_VERSION && poetry install --no-dev
        --no-interaction --no-ansi
      directory: services/polland
      name: install cmd
  name: "DZ Services"
  id: devzero-services
  description: This quick start recipe builds a workspace with an instance of the DevZero services repo.
  packages:
    - dz.docker
    - nixpkgs.direnv
    - nixpkgs.gcc
    - nixpkgs.go
    - nixpkgs.kubernetes
    - nixpkgs.musl
    - nixpkgs.musl.dev
    - nixpkgs.python310
    - nixpkgs.rustup
    - nixpkgs.jq
  repos:
    - https://github.com/devzero-inc/services
