---
properties:
  id:
    type: string
  name:
    type: string
  description:
    type: string
  cover_image:
    type: string
    format: uri
  repos:
    type: array
    items:
      $ref: "#/definitions/Repo"
  author:
    name:
      type: string
  packages:
    type: array
  commands:
    type: array
definitions:
  Repo:
    type: object
    properties:
      name:
        type: string
      repo_url:
        type: string
