id:
  type: string
name:
  type: string
description:
  type: string
cover_image:
  type: string
  format: uri
repos:
  type: array
  items:
    type: object
    properties:
      name:
        type: string
      repo_url:
        type: string
author:
  name:
    type: string
packages:
  type: array
  items:
    type: string
commands:
  type: array
  items:
    type: object
    properties:
      shell: string
      name: string
      directory: string
